### ISSUE TITLE
Ability to ignore revision number

### ISSUE THREAD

**Issue by kijube** [seddik/oversion#1]
Hi!
Thanks for creating this extension!
 I was wondering if you could add the ability to not enter a revision number (like version 1.0.15 instead of 1.0.15.0).

**Comment by seddik** [comment]
@kijube I really don't have time for now, but I'll add that as soon as I can, I promise. in the meantime feel free to add a pull request for this option.

**Comment by seddik** [comment]
@kijube you'll be able to ignore minor/build and revision number now
