### ISSUE TITLE
Cannot seem to get oVersion to work in Visual Studio 2022

### ISSUE THREAD

**Issue by JohnHenderson1963** [seddik/oversion#3]
I have installed oVersion through Visual Studio market place, but it doesnt seem to work for me?

![image](https://user-images.githubusercontent.com/63504024/141649256-d18697d1-220e-495b-867f-e386cfc7d2e9.png)

I expected it to auto increment, Have I got it wrong?

**Comment by seddik** [comment]
No it doesn't do that, it just make changing the version easier, as it was released for VS2022 before any other Version changer. that feature may be added in the future.

**Comment by seddik** [comment]
#5
